Replace the last instance of `throw()` with `noexcept`. NFC.
Fixes a -Wdeprecated warning.

/home/travis/build/Quuxplusone/googletest/googletest/test/googletest-death-test_ex_test.cc:62:28: error:
      dynamic exception specifications are deprecated [-Werror,-Wdeprecated]
  const char* what() const throw() override { return "exceptional message"; }
                           ^~~~~~~
/home/travis/build/Quuxplusone/googletest/googletest/test/googletest-death-test_ex_test.cc:62:28: note:
      use 'noexcept' instead
  const char* what() const throw() override { return "exceptional message"; }
                           ^~~~~~~
                           noexcept